# Generated by Django 3.0.1 on 2020-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('introduction', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=140)),
                ('equip', models.CharField(max_length=100)),
                ('equip_picture', models.ImageField(blank=True, upload_to='equip')),
                ('sns', models.URLField(blank=True)),
                ('profile', models.ImageField(blank=True, upload_to='profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
