# Generated by Django 3.0.1 on 2020-01-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='portfolio',
            new_name='file',
        ),
    ]
